api/urls.py
from django.conf.urls import url
import views

app_name = 'api'

urlpatterns = [
    url('get_tag_length/(?P<tag>[\w]+)', views.get_tag_length, name='get_tag_length')
]

blog/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from django.contrib.auth import views as auth_views
import views

router = routers.DefaultRouter()
router.register(r'article', views.ArticleViewSet, base_name='ArticleViewSet')

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.blog_list, name='list'),
    url(r'^login$', views.login, name='login'),
    url(r'^detail/(?P<slug>[-\w]+)', views.detail, name='detail'),
    url(r'^filter/(?P<tag>[\w]+)', views.filter, name='filter'),
    url(r'^resume/(?P<slug>[-\w]+)', views.cv, name='cv'),
    # url(r'^api/blog/(?P<pk>[0-9]+)/', views.detail, name='aa'),
    url(r'^docs/', include('rest_framework_swagger.urls')),
    url(r'^login/$', auth_views.login),
    url(r'^api/', include(router.urls)),
]

zcy_md/urls.py
""" Define preview URL. """

from django.conf.urls import patterns, url

from .views import preview

urlpatterns = [
    url('preview/$', preview, name='django_markdown_preview')
]

zhaochy_cn/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
    url(r'^markdown/', include('zcy_md.urls')),
    url(r'^post/', include('posts.urls')),
    # url(r'^api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals
from django.utils.encoding import smart_unicode
from django.db import models
from zcy_md.models import MarkdownField
from django.core.urlresolvers import reverse


# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=200, primary_key=True)

    def __unicode__(self):
        return smart_unicode(self.name)

        # def __str__(self):
        # print smart_unicode(self.name)
        # return smart_unicode(self.name)


        # class Meta:
        #     def get_Article_num(self):
        #         return Article.objects.filter(tag=self.name).count()


class Article(models.Model):
    title = models.CharField(max_length=200)
    content = MarkdownField()
    slug = models.SlugField(max_length=200, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    publish = models.BooleanField(default=False)
    tag = models.ForeignKey('blog.Tag', on_delete=models.SET_NULL, null=True)

    def __unicode__(self):
        return smart_unicode(self.title)

    class Meta:
        ordering = ['-modified']

    def get_absolute_url(self):
        return "/api/blog/%i/" % self.id


class Resume(models.Model):
    title = models.CharField(max_length=200)
    content = MarkdownField()
    slug = models.SlugField(max_length=200, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return smart_unicode(self.title)

blog/views.py
# coding=utf8

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render
import datetime
from rest_framework import viewsets
from serializers import ArticleSerializer
from models import *


# Create your views here.

def index(request):
    return render(request, 'blog/index.html')


def blog_list(request):
    """
    blog index
    获取博客的文章列表
    """
    now = datetime.datetime.now()
    queryset = Article.objects.all().filter(publish=True)
    paginator = Paginator(queryset, 5)  # show 5 obj per page
    page_request_var = 'page'
    page = request.GET.get(page_request_var)

    try:
        objects = paginator.page(page)
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)
    tags = Tag.objects.all()
    context = {
        "object_list": objects,
        "tags": tags,
        'page_request_var': page_request_var
    }
    return render(request, 'blog/list.html', context)


def filter(request, tag=None):
    tags = Tag.objects.all()
    # start_date = datetime.date(2016, 5, 30)
    # end_date = datetime.date(2016, 6, 30)
    queryset = Article.objects.filter(tag=tag, publish=True).order_by('created')
    # print Tag.objects.filter(name=tag).count()
    # print queryset.count()
    context = {
        "object_list": queryset,
        "tags": tags
    }
    return render(request, 'blog/list.html', context)


def login(request):
    # if request.user.is_authenticated()
    if request.method == 'GET':
        return render(request, 'blog/login.html')
    elif request.method == 'POST':
        return render(request, 'blog/index.html')


def detail(request, slug):
    # print slug
    try:
        obj = Article.objects.get(slug=slug, publish=True)
        # print obj.get_absolute_url()
    except Exception, e:
        print (e.message)
        # return render(request,)
        return render(request, 'blog/list.html')
    context = {
        "object": obj
    }
    return render(request, 'blog/detail.html', context)


def cv(request, slug):
    queryset = Resume.objects.all()
    try:
        obj = Resume.objects.get(slug=slug)
    except Exception, e:
        return render(request, 'blog/list.html')
    context = {
        "object": obj
    }
    return render(request, 'blog/detail.html', context)


class ArticleViewSet(viewsets.ModelViewSet):
    serializer_class = ArticleSerializer

    def get_queryset(self):
        return Article.objects.all()

templates/blog/base.html
{% extends 'base.html' %}
{% block ng_module %}blog{% endblock %}
{% block static_header %}
    {% include 'blog/statics.html' %}
{% endblock %}

templates/blog/detail.html
{% extends "blog/base.html" %}
{% load django_markdown %}
{% block content %}
    <div class="container content">
        <div class="col-sm-offset-1 col-sm-10 col-sm-offset-1">
            <center><h1>{{ object.title }}</h1></center>
            <center>
                <small>{{ object.modified|date:"Y-m-d H:i" }}</small>
            </center>
            <hr>
            {{ object.content|markdown }}
        </div>
    </div>
{% endblock %}

templates/blog/list.html
{% extends 'blog/base.html' %}
{% load django_markdown %}
{% block content %}
    <div class="container content">
        <div class="col-sm-offset-1 col-sm-6">
            {% for object in object_list %}
                <div>
                    <div>
                        <h1><a href="{% url 'blog:detail' object.slug %}">{{ object.title }}</a></h1>
                    </div>
                    <div>
                        <em id="update_time" style="color: #8a6d3b">更新于：{{ object.modified|date:"Y-m-d H:i" }}</em>
                    </div>
                    <div>
                        {{ object.content|markdown|striptags|safe|truncatechars:150|linebreaks }}
                    </div>
                    <hr>
                </div>
            {% endfor %}
            <nav>
                <ul class="pagination">
                    {% if object_list.has_previous %}
                        <li>
                            <a href="?page={{ object_list.previous_page_number }} " aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="disabled"><a><span aria-hidden="true">&laquo;</span></a></li>
                    {% endif %}

                    {% for obj in object_list.paginator.page_range %}
                        {% if object_list.number == obj %}
                            <li class="active"><a href="#">{{ obj }}</a></li>
                        {% else %}
                            <li><a href="?{{ page_request_var }}={{ obj }}">{{ obj }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if object_list.has_next %}
                        <li><a href="?{{ page_request_var }}={{ object_list.next_page_number }}"><span
                                aria-hidden="true">&raquo;</span></a></li>
                    {% else %}
                        <li class="disabled"><a><span aria-hidden="true">&raquo;</span></a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>

        <div class="col-sm-2 col-sm-offset-1" ng-controller="TagController">
            <h2>Tags</h2>
            {% for tag in tags %}
                <a href="{% url 'blog:filter' tag.name %}">{{ tag.name }}</a><br>
            {% endfor %}
        </div>


    </div>

{% endblock %}

templates/blog/login.html
{% extends 'blog/base.html' %}
{% block content %}
<form method="post" action="">
{% csrf_token %}
    <label for="username">Password:</label>
    <input type="text" placeholder="username">
    <br>
    <label for="password">Password:</label>
    <input id="password" type="password" placeholder="password">
    <input type="submit" value="submit">
</form>
{% endblock %}

templates/blog/statics.html
{% load staticfiles %}

<script src="{% static 'blog/js/angular_root.js' %}" type="text/javascript"></script>
<script src="{% static 'blog/js/NavbarController.js' %}" type="text/javascript"></script>
<script src="{% static 'blog/js/TagController.js' %}" type="text/javascript"></script>