api/urls.py
from django.conf.urls import url
import views

app_name = 'api'

urlpatterns = [
    url('get_tag_length/(?P<tag>[\w]+)', views.get_tag_length, name='get_tag_length')
]

blog/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from django.contrib.auth import views as auth_views
import views

router = routers.DefaultRouter()
router.register(r'article', views.ArticleViewSet, base_name='ArticleViewSet')

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.blog_list, name='list'),
    url(r'^login$', views.login, name='login'),
    url(r'^detail/(?P<slug>[-\w]+)', views.detail, name='detail'),
    url(r'^filter/(?P<tag>[\w]+)', views.filter, name='filter'),
    url(r'^resume/(?P<slug>[-\w]+)', views.cv, name='cv'),
    # url(r'^api/blog/(?P<pk>[0-9]+)/', views.detail, name='aa'),
    url(r'^docs/', include('rest_framework_swagger.urls')),
    url(r'^login/$', auth_views.login),
    url(r'^api/', include(router.urls)),
]

posts/urls.py
from django.conf.urls import url
import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.post_list, name='index'),
    url(r'^create/$', views.post_create),
    url(r'^(?P<id>\d+)/$', views.post_detail, name='detail'),
    url(r'^(?P<id>\d+)/edit/$', views.post_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', views.post_delete),
]

zcy_md/urls.py
""" Define preview URL. """

from django.conf.urls import patterns, url

from .views import preview

urlpatterns = [
    url('preview/$', preview, name='django_markdown_preview')
]

zhaochy_cn/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
    url(r'^markdown/', include('zcy_md.urls')),
    url(r'^post/', include('posts.urls')),
    # url(r'^api/', include('api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% include 'statics.html' %}
    {% block static_header %}{% endblock %}
</head>
<body ng-app="{% block ng_module %}{% endblock %}">

{% include 'navbar.html' %}
{% block content %}{% endblock %}

{% block static_footer %}{% endblock %}

{% include 'footer.html' %}
</body>
</html>

templates/footer.html
{% load staticfiles %}
<div class="footer" style="background-color: #2a3333">
    <div class="container text-muted">
        <div class="col-md-3 col-md-offset-1">
            <hr>
            <p>The articles of this site is provided by zhaochy, a master student of CAS. All the articles of this site
                are provided without warranty of any kind. Permission of all the articles of this site is hereby
                granted, free of charge, to any person obtaining a copy of all the articles and files, to deal the
                articles without restriction.</p>
        </div>
        <div class="col-md-3 col-md-offset-1">
            <div class="footImg"><h3>STAY CONNECTED</h3></div>
            <hr/>
            <p> Feel free to contact me at any time.
            </p>
            <p>QQ:359713842 </p>
            <p><a style="text-decoration: none; color: inherit;" href="mailto:zhaochy_2015@hotmail.com">Email:zhaochy_2015@hotmail.com</a>
            </p>
        </div>
        <div class="col-md-3 col-md-offset-1">
            <div class="footImg text-muted"><h3>Copyright</h3></div>
            <hr/>
            <p class="text-muted">Copyright 2016 zhaochy.cn 陕ICP备15007631号-1 - All RIghts Reserved</p>
        </div>
    </div>
</div>

templates/navbar.html
<div class="navbar navbar-default" ng-controller="NavbarController">
    <div class="container">
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {#                <li class="" id="index"><a href="{% url 'blog:index' %}">Index</a></li>#}
                <li id="blog"><a href="{% url 'blog:list' %}">Blog</a></li>
                <li><a href="{% url 'blog:cv' 'en' %}">My Resume</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if  user.is_authenticated %}
                    <li><a href="{% url 'admin:index' %}">{{ user.username }}</a></li>
                {% else %}

                    <li><a href="{% url 'admin:login' %}">login</a></li>
                    <li><a href="#">register</a></li>

                {% endif %}
            </ul>
        </div>
    </div>
</div>

templates/statics.html
{% load staticfiles %}

<link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'blog/css/main.css' %}" rel="stylesheet">

{# for production use of angular #}
{#<script src="{% static 'blog/js/angular.min.js' %}" type="text/javascript"></script>#}
{#<script src="{% static 'blog/js/jquery-2.1.4/jquery.min.js' %}" type="text/javascript"></script>#}

{# for develop use #}
<script src="{% static 'blog/js/angular-1.5.5/angular.js' %}" type="text/javascript"></script>
<script src="{% static 'blog/js/angular-1.5.5/angular-route.js' %}" type="text/javascript"></script>
<script src="{% static 'blog/js/jquery-2.1.4/jquery.js' %}" type="text/javascript"></script>